src = [
  'combinatorics.cpp',
  'crypto.cpp',
  'exponentiation.cpp',
  'gcd.cpp',
  'graph.cpp',
  'hash.cpp',
  'interpolation.cpp',
  'modulo.cpp',
  'newton.cpp',
  'primes.cpp',
  'random.cpp',
  'search.cpp',
  'sort.cpp',
  'table.cpp',
  'trees.cpp',
]

lib = library(
  'n-methods',
  src,
  include_directories: inc_dir,
  install: true
)
